locals {
  # Define module paths
  module_paths = {
    vpc                = "../../modules/vpc"
    security_groups    = "../../modules/security_groups"
    iam               = "../../modules/iam"
    s3                = "../../modules/s3"
    alb               = "../../modules/alb"
    asg               = "../../modules/asg"
    enhanced_security = "../../modules/enhanced_security"
    enhanced_monitoring = "../../modules/enhanced_monitoring"
    zero_trust_network = "../../modules/zero_trust_network"
    kms               = "../../modules/kms"
    secrets_manager   = "../../modules/secrets_manager"
    state_management  = "../../modules/state_management"
  }

  # Define module dependencies
  module_dependencies = {
    security_groups = ["vpc"]
    alb            = ["vpc", "security_groups"]
    asg            = ["vpc", "alb", "security_groups", "iam"]
    enhanced_security = ["vpc"]
    zero_trust_network = ["vpc"]
    secrets_manager = ["kms"]
  }
}

# Generate module configurations
generate "modules" {
  path      = "modules.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
# This file is auto-generated by Terragrunt
# Module configurations will be generated here
EOF
} 